version: '3.8'

services:
  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  api:
    build: ./api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build: ./client
    env_file:
      - .env
    ports:
      - "8081:8081"
    depends_on:
      - api

volumes:
  db_data:
